# Supplementary Information {#sec-supp}

\setcounter{figure}{0}
\renewcommand{\figurename}{Fig.}
\renewcommand{\thefigure}{S\arabic{figure}}

```{r}
#| echo: false
#| message: false
#| warning: false
library(magick)
```

```{r}
#| label: fig-snowmelt-shift
#| echo: false
#| message: false
#| fig-cap: |
#|   Decadal trend in snowmelt timing (2011–2021).  
#|   Changes in snowmelt Day of Year (DOY) relative to 2011 (set as 0). A total of 1,000 pixels were randomly sampled and plotted. Despite large interannual fluctuations, an overall trend toward earlier snowmelt is suggested. Data for 2019 are missing due to construction work at the mountain lodge where the camera was installed.
#| out-width: 100%
#| fig-align: center
image_read("files/snowmelt_shifting.png")
```

```{r}
#| label: fig-snowmelt-map
#| echo: false
#| message: false
#| fig-cap: |
#|   Predicted snowmelt DOY (linear regression for each cell).  
#|   Predicted snowmelt DOY for 2012, 2021, and 2030, derived from cell-wise linear regression models fitted to annual snowmelt DOY between 2011 and 2021.   
#| out-width: 100%
#| fig-align: center
image_read("files/snowmelt_doy.png")
```

```{r}
#| label: fig-snowmelt-shift-map
#| echo: false
#| message: false
#| fig-cap: |
#|   Changes in predicted snowmelt DOY (2021 – 2012; negative values indicate earlier snowmelt).  
#|   Difference in predicted snowmelt DOY between 2012 and 2021. Most areas show earlier snowmelt, with clear spatial heterogeneity in the degree of change.   
#| out-width: 100%
#| fig-align: center
image_read("files/snowmelt_shift_map.png")
```